### ISSUE TITLE
There is no source code!

### ISSUE THREAD

**Issue by cansik** [maechler/sna#1]
Would be great to see some source code :dancer: !

:space_invader: :cat: :coffee:

**Comment by maechler** [comment]
After the final release of version 1.0 I think we will have time to address this issue. I guess source code could be integrated in version 1.1 or at the latest 1.2.

Thanks for your contribution!

**Comment by cansik** [comment]
:+1:

**Comment by maechler** [comment]
Fixed this issue with the following commit: https://github.com/maechler/sna/commit/316cd2ea10e3dc7124d9e17b9abf37c091b073e8
